Breaking Change - #5 New Stage Added to the WA

diff --git a/.github/workflows/docker-aws-k6-pipeline.yml b/.github/workflows/docker-aws-k6-pipeline.yml
--- a/.github/workflows/docker-aws-k6-pipeline.yml
+++ b/.github/workflows/docker-aws-k6-pipeline.yml
@@ -34,7 +34,7 @@ env:
   TASK_FAMILY: ${{ secrets.TASK_FAMILY }}
   INFLUXDB_USER: "admin"
   INFLUXDB_PASS: "admin123"
-  INFLUXDB_URL: "3.144.130.123"
+  INFLUXDB_URL: "3.144.130.123:8086"
   INFLUXDB_DB: "mydb"
 
 jobs:
@@ -85,15 +85,15 @@ jobs:
          
           fi
 
-          CURRENT_VERSION=$(jq -r '.version // "0.0.0"' package.json)
-          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
-
           case "$VERSION_BUMP" in
             major)
               ((MAJOR+=1))
+              MINOR=0
+              PATCH=0
               ;;
             minor)
               ((MINOR+=1))
+              PATCH=0
               ;;
             patch|*)
               ((PATCH+=1))
@@ -262,55 +262,57 @@ jobs:
           path: k6-results/
 
       # Optional: Fail workflow if performance thresholds are violated
-      # - name: Check thresholds
-      #   if: failure()
-      #   run: |
-      #     echo "❌ Performance thresholds failed. Please check k6 results."
-      #     exit 1
-  # deploy:
-  #   runs-on: ubuntu-latest
-  #   needs: build_and_push   # 👈 deploy only happens if build_and_push pass
-  #   steps:
-  #     - name: Configure AWS credentials
-  #       uses: aws-actions/configure-aws-credentials@v4
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         aws-region: ${{ env.AWS_REGION }}
+      - name: Check thresholds
+        if: failure()
+        run: |
+          echo "❌ Performance thresholds failed. Please check k6 results."
+          exit 1
+
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build_and_push   # 👈 deploy only happens if build_and_push pass
+    steps:
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
           
 
-  #     - name: Install jq
-  #       run: sudo apt-get update && sudo apt-get install -y jq
+      - name: Install jq
+        run: sudo apt-get update && sudo apt-get install -y jq
 
-  #     - name: Update ECS Task Definition
-  #       run: |
-  #         echo "$IMAGE_NAME:$TAG";
-  #         FULL_IMAGE="${{ needs.build_and_push.outputs.full_image }}"
-  #         echo "Using image: $FULL_IMAGE"
+      - name: Update ECS Task Definition
+        run: |
+          echo "$IMAGE_NAME:$TAG";
+          FULL_IMAGE="${{ needs.build_and_push.outputs.full_image }}"
+          echo "Using image: $FULL_IMAGE"
 
-  #         aws ecs describe-task-definition --task-definition "$TASK_FAMILY" --query taskDefinition > td.json
-  #         jq --arg IMAGE "$FULL_IMAGE" '
-  #           .containerDefinitions[0].image = $IMAGE
-  #           | {
-  #               family: .family,
-  #               networkMode: .networkMode,
-  #               executionRoleArn: .executionRoleArn,
-  #               containerDefinitions: .containerDefinitions,
-  #               requiresCompatibilities: .requiresCompatibilities,
-  #               cpu: .cpu,
-  #               memory: .memory
-  #             }
-  #           + (if .taskRoleArn != null then {taskRoleArn: .taskRoleArn} else {} end)
-  #         ' td.json > new-td.json
-  #         aws ecs register-task-definition --cli-input-json file://new-td.json
+          aws ecs describe-task-definition --task-definition "$TASK_FAMILY" --query taskDefinition > td.json
+          jq --arg IMAGE "$FULL_IMAGE" '
+            .containerDefinitions[0].image = $IMAGE
+            | {
+                family: .family,
+                networkMode: .networkMode,
+                executionRoleArn: .executionRoleArn,
+                containerDefinitions: .containerDefinitions,
+                requiresCompatibilities: .requiresCompatibilities,
+                cpu: .cpu,
+                memory: .memory
+              }
+            + (if .taskRoleArn != null then {taskRoleArn: .taskRoleArn} else {} end)
+          ' td.json > new-td.json
+          aws ecs register-task-definition --cli-input-json file://new-td.json
 
-  #     - name: Deploy to ECS
-  #       run: |
-  #         aws ecs update-service \
-  #           --cluster "$ECS_CLUSTER" \
-  #           --service "$ECS_SERVICE" \
-  #           --task-definition "$TASK_FAMILY" \
-  #           --force-new-deployment
-  #         aws ecs wait services-stable \
-  #           --cluster "$ECS_CLUSTER" \
-  #           --services "$ECS_SERVICE"
+      - name: Deploy to ECS
+        run: |
+          aws ecs update-service \
+            --cluster "$ECS_CLUSTER" \
+            --service "$ECS_SERVICE" \
+            --task-definition "$TASK_FAMILY" \
+            --force-new-deployment
+          aws ecs wait services-stable \
+            --cluster "$ECS_CLUSTER" \
+            --services "$ECS_SERVICE"
